### ISSUE TITLE
Snapshots

### ISSUE THREAD

**Issue by farzadmf** [jacqueskang/EventSourcing#27]
Hi Jacques,

I recently stumbled upon your library when going through stackoverflow, and I must say I'm very impressed. Great work!

I was wondering whether you're planning to include snapshot capability to the library.

Cheers

**Comment by jacqueskang** [comment]
Thank you!
Indeed snapshot capability is nice to have, but I currently have limited knowledge and experience with it.
I'll consider this be a missing feature

**Comment by farzadmf** [comment]
Thank you for your reply,

Maybe I'll try to do something, and if I'm satisfied with what I have, I could open a PR

**Comment by jacqueskang** [comment]
@farzadmf Awesome I really appreciate it!
