### ISSUE TITLE
Handling concurrency

### ISSUE THREAD

**Issue by REEDOOX** [jacqueskang/EventSourcing#39]
Does this sample handle concurrency ?

Let's say I created a gift card with an initial value of 100 and executed two request at the same time to debit 40 points for the first request and 50 points for the second request.
I might end up with a gift card value of 60 or 50 after the two operations have been processed. Is this possible ?

Thanks in advance

**Comment by jacqueskang** [comment]
@REEDOOX 
It can happen that 2 parallel threads/processes create different events with a same version, then it will be the responsibility of event store to detect the conflit and throw exception. If you use DynamoDB and correctly configure the partition/sort keys it will do the job.

**Comment by REEDOOX** [comment]
@jacqueskang  thank you for the quick reply. How about when using Sql Server? Any ideas?

**Comment by jacqueskang** [comment]
sql server event store detects conflits too with primary key.
See src/JKang.EventSourcing.Persistence.EfCore/EventEntityConfiguration.cs
